# scanning linux machines against CVE-2024-3094
#
# This play will not patch affected systems, it will only scann and add
# affected hosts to your inventory in seperated groups.
---

- name: scan against CVE-2024-3094
  block:
    - ansible.builtin.command: 'command -v xz | head -n 1 | rev | cut -d " " -f 1 | rev'
      register: vuln

    - ansible.builtin.add_host:
        name: '{{ inventory_hostname }}'
        groups:
          - vuln
          - cve-2024-3094
        when: ( vuln.stdout is version('5.6.0', '>=') ) and
              ( vuln.stdout is version('5.6.2', '<=') )
