---

- name: check kernel against CVE-2024-1086
  block:
    - ansible.builtin.shell:
        command: |
           version = $(uname -r)
          if [[ ${version} == *"-"* ]]; then
              version=$(echo ${version} | cut -d '-' -f1)
          fi
          echo ${version}
      register: kernel-version
